# Configuration items needed:
#   Port
#   Setting repository path
#   Authentication stuff:
#     - Disable user Authentication
#     - Enable "login as guest"
#       > Having both enabled should default to a very low-level role ("Default") for all
#   Roles/Permisisons concepts:
#     - Admin role
#       > View and manage jobs, requests, and system loggings (error and debug)
#       > Edit and manitain metadata without going through requests
#     - Guest role
#       > Only can view/listen to music.  No server editing whatsoever
#             (how can this be secured?).
#     - Default role
#       > Things to notifiy server admin/setup-er:
#         ~ Permissions must be kept low-level to not risk unwarrented server greifing
#         ~ This role is the only applied role if both "Disable user auth" and
#               "Enable login as guest" is enabled
#   Future:
#     Logging settings for repository
#     Multiple routings with specialized parameters
#       - Have only certain songs be accessible via that routing
#       - Have certain permissions (user auth requ, or none)
#     Multiple repositories (why would it be useful?)
#       - Physically seperate certain songs in different locations in file-system
#         > Can be nice in a multiple drive scenario

Repository_Settings:
  # File system path to store the repository folder.
  path: ''
Server_Settings:
  # The port the server will run on.
  port: 3000
  # UNIMPLEMENTED
  # authentication:
  #   # Enable the option to login as a guest at the login screen.  All guests
  #   #   will be given the same permissions specified via the guest role (set via
  #   #   the 'guest_role' option).
  #   # This option is useless if disable_user_authentication is enabled.
  #   enable_login_as_guest: false
  #   # Disable the need for user authentication altogether.
  #   # NOTICE: If disable_user_authentication is enabled, all connected uses
  #   #   will be given the same permissions specified via the default role (set
  #   #   via the 'default_role' option).
  #   #   THIS OPTION is NOT recommended for security.
  #   disable_user_authentication: false
  # roles:
  #   - name: 'Admin'
  #   - name: 'Guest'
  #     guest_role: true
  #   - name: 'Default'
  #     default_role: true
